# Generated by Django 4.0.4 on 2022-04-22 03:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('User', django.db.models.manager.Manager()),
            ],
        ),
    ]
